"""Itinéraires thématiques (« routes ») à travers l'archipel."""

ITINERARIES = [
    dict(
        slug="grand-tour-des-quatre-iles",
        name="Le grand tour des quatre îles",
        theme="Découverte",
        duration="14 à 16 jours",
        islands=["grande-comore", "moheli", "anjouan", "mayotte"],
        hero="lagon_choungui",
        card="moroni_panorama",
        lead="L'itinéraire complet pour comprendre l'archipel : un volcan, une réserve de biosphère, l'île aux parfums et un lagon géant.",
        days=[
            ("Jours 1-2", "Moroni et la médina", "Arrivée à Hahaya, installation à Moroni. Visite de la médina, des mosquées du Vendredi et du marché de Volo Volo. Coucher de soleil à Itsandra.", "moroni"),
            ("Jours 3-4", "Ascension du Karthala", "Départ à l'aube avec un guide, bivouac près du cratère, lever de soleil sur la caldeira et descente.", "karthala"),
            ("Jour 5", "Le Nord de la Grande Comore", "Plages de Mitsamiouli et Maloudja, Trou du Prophète et tour du lac Salé.", "nord-grande-comore"),
            ("Jours 6-8", "Mohéli, l'île nature", "Vol ou bateau vers Fomboni. Journée aux îlots de Nioumachoua, nuit à Itsamia pour observer la ponte des tortues.", "parc-national-moheli"),
            ("Jours 9-11", "Anjouan, l'île aux parfums", "Mutsamudu et sa citadelle, Domoni, visite d'une distillerie d'ylang-ylang et randonnée au lac Dzialandzé.", "mutsamudu"),
            ("Jours 12-15", "Mayotte et son lagon", "Petite-Terre et lac Dziani, journée en mer dans le lagon, snorkeling avec les tortues à N'Gouja, ascension du mont Choungui.", "lagon-de-mayotte"),
            ("Jour 16", "Départ", "Vol retour depuis Pamandzi (Mayotte) ou retour vers Moroni selon votre billet.", None),
        ],
        tips="Les liaisons inter-îles (avion ou bateau) changent souvent : réservez-les en premier et gardez une journée tampon en cas d'annulation.",
    ),
    dict(
        slug="volcans-et-sommets",
        name="Volcans & sommets",
        theme="Aventure",
        duration="8 à 10 jours",
        islands=["grande-comore", "anjouan", "mayotte"],
        hero="karthala",
        card="karthala_lave",
        lead="Pour les marcheurs : le cratère du Karthala, la forêt de nuages du Ntingui et le belvédère du Choungui.",
        days=[
            ("Jour 1", "Arrivée à Moroni", "Préparation du matériel, rencontre avec le guide, balade dans la médina.", "moroni"),
            ("Jours 2-3", "Le Karthala", "Montée par la forêt et la lande de bruyères, bivouac au bord de la caldeira, descente par un autre versant.", "karthala"),
            ("Jour 4", "Récupération au nord", "Baignade et repos sur les plages du nord de la Grande Comore.", "nord-grande-comore"),
            ("Jours 5-7", "Anjouan, au cœur des montagnes", "Randonnée vers le lac Dzialandzé puis les crêtes du mont Ntingui, nuit chez l'habitant dans les hauts.", "lac-dzialandze-et-ntingui"),
            ("Jours 8-10", "Mayotte, entre sommets et lagon", "Mont Choungui au lever du soleil, tour du lac Dziani sur Petite-Terre, randonnée vers le mont Bénara.", "mont-choungui"),
        ],
        tips="Partez en saison sèche (mai à octobre) et réservez des guides locaux expérimentés à l'avance.",
    ),
    dict(
        slug="lagons-et-tortues",
        name="Lagons & tortues",
        theme="Océan",
        duration="10 à 12 jours",
        islands=["mayotte", "moheli"],
        hero="tortue_ngouja",
        card="ngouja",
        lead="Un voyage les pieds dans l'eau, à la rencontre des tortues, des baleines et des récifs les mieux préservés de l'archipel.",
        days=[
            ("Jours 1-2", "Petite-Terre", "Arrivée à Pamandzi, tour du lac Dziani et plage de Moya.", "petite-terre-et-lac-dziani"),
            ("Jours 3-5", "Le lagon de Mayotte", "Sortie baleines et dauphins (en saison), plongée dans la passe en S, pique-nique sur un îlot de sable blanc.", "lagon-de-mayotte"),
            ("Jours 6-7", "Le sud de Mayotte", "Snorkeling avec les tortues à N'Gouja, sentiers de Saziley.", "ngouja"),
            ("Jours 8-10", "Mohéli", "Îlots de Nioumachoua, mangrove en kayak et observation des baleines.", "parc-national-moheli"),
            ("Jours 11-12", "Itsamia", "Nuits d'observation de la ponte des tortues avec les écoguides du village.", "itsamia"),
        ],
        tips="Pour les baleines, visez août-septembre. Emportez votre masque et un lycra anti-UV.",
    ),
    dict(
        slug="route-des-sultans",
        name="Sur la route des sultans",
        theme="Culture",
        duration="7 à 9 jours",
        islands=["grande-comore", "anjouan", "mayotte"],
        hero="moroni_ancienne_mosquee",
        card="mutsamudu_rue",
        lead="Médinas, citadelles, mosquées anciennes et palais : un voyage dans l'histoire des cités marchandes de l'océan Indien.",
        days=[
            ("Jours 1-2", "Moroni", "Médina, ancienne mosquée du Vendredi, vieux port, puis Itsandra, ancienne cité royale.", "moroni"),
            ("Jour 3", "Iconi et le sud", "La falaise d'Iconi, mémoire des razzias, et les villages du Badjini.", None),
            ("Jours 4-6", "Mutsamudu et Domoni", "Citadelle, médina et palais de Mutsamudu, puis la vieille ville de Domoni et ses tombeaux.", "mutsamudu"),
            ("Jours 7-8", "Mayotte", "Mosquée de Tsingoni et son mihrab du XVIe siècle, marché de Mamoudzou, rocher de Dzaoudzi.", "mamoudzou-et-tsingoni"),
        ],
        tips="Si vous voyagez en juillet ou en août, demandez s'il est possible d'assister à un grand mariage.",
    ),
    dict(
        slug="escapade-a-deux-a-moheli",
        name="Escapade à deux à Mohéli",
        theme="Romantique",
        duration="5 à 6 jours",
        islands=["moheli"],
        hero="nioumachoua_ilots",
        card="nioumachoua_mangrove",
        lead="Un écolodge face aux îlots, des plages désertes et des nuits étoilées : la plus douce des parenthèses.",
        days=[
            ("Jour 1", "Arrivée à Mohéli", "Accueil à Fomboni et transfert vers un écolodge du sud de l'île.", None),
            ("Jour 2", "Les îlots de Nioumachoua", "Journée en barque, snorkeling et déjeuner de poisson grillé sur un îlot.", "parc-national-moheli"),
            ("Jour 3", "Forêt et lac", "Randonnée tranquille vers le lac Dziani Boundouni, à l'écoute des oiseaux.", "forets-et-lacs-de-moheli"),
            ("Jours 4-5", "Itsamia", "Nuit au village et observation des tortues sous les étoiles.", "itsamia"),
            ("Jour 6", "Retour", "Matinée libre et retour vers Fomboni.", None),
        ],
        tips="Mohéli est très calme : apportez livres et espèces, et laissez-vous gagner par le rythme de l'île.",
    ),
]

ITINERARIES_BY_SLUG = {i["slug"]: i for i in ITINERARIES}
