"""Glossaire, quiz et « Le saviez-vous ? »."""

GLOSSARY = [
    ("Anda", "Grand mariage coutumier de la Grande Comore, qui fait accéder le marié au rang de notable.", "culture/coutumes-et-rites.html"),
    ("Boutre", "Voilier traditionnel en bois de l'océan Indien, longtemps utilisé pour le commerce entre l'Arabie, l'Afrique et l'archipel.", "histoire/premiers-peuplements.html"),
    ("Caldeira", "Vaste dépression au sommet d'un volcan, formée par l'effondrement de sa chambre magmatique. Celle du Karthala est l'une des plus grandes du monde.", "geographie/volcans-et-reliefs.html"),
    ("Chiromani", "Pièce de tissu drapée, souvent rouge et blanche, portée par les femmes d'Anjouan.", "culture/artisanat-et-costumes.html"),
    ("Cœlacanthe", "Poisson « fossile vivant » apparu il y a plus de 400 millions d'années, qui vit dans les eaux profondes des Comores.", "geographie/faune-et-flore.html"),
    ("Debaa", "Chant religieux dansé par les femmes à Mayotte, en l'honneur du Prophète.", "culture/musique-et-danses.html"),
    ("Djinn", "Esprit invisible des croyances musulmanes et populaires, très présent dans les contes.", "culture/contes-et-legendes.html"),
    ("Djoho", "Manteau d'apparat brodé porté par les hommes lors des cérémonies.", "culture/artisanat-et-costumes.html"),
    ("Hirimu", "Classe d'âge regroupant les hommes d'un même village en Grande Comore.", "culture/coutumes-et-rites.html"),
    ("Kashkazi", "Saison chaude et humide (novembre à avril), portée par la mousson de nord-ouest.", "geographie/climat-et-saisons.html"),
    ("Kibushi", "Langue d'origine malgache parlée dans plusieurs villages de Mayotte.", "culture/langues.html"),
    ("Kofia", "Calotte brodée à la main portée par les hommes.", "culture/artisanat-et-costumes.html"),
    ("Kusi", "Saison fraîche et sèche (mai à octobre), dominée par les alizés de sud-est.", "geographie/climat-et-saisons.html"),
    ("Lagon", "Étendue d'eau peu profonde séparée de l'océan par une barrière de corail. Celui de Mayotte couvre environ 1 100 km².", "geographie/ocean-et-lagons.html"),
    ("Manzaraka", "Grand mariage mahorais.", "culture/coutumes-et-rites.html"),
    ("Maoulid", "Fête de la naissance du Prophète, célébrée par des chants et récitations collectifs.", "culture/fetes-et-religion.html"),
    ("Mataba", "Plat de feuilles de manioc pilées et mijotées au lait de coco.", "culture/cuisine.html"),
    ("Médina", "Vieille ville aux ruelles étroites, héritage des cités swahilies.", "histoire/le-temps-des-sultans.html"),
    ("Mila na ntsi", "Système coutumier de la Grande Comore, littéralement « les us et le pays ».", "culture/coutumes-et-rites.html"),
    ("Msindzano", "Masque de beauté à base de bois de santal râpé sur du corail.", "culture/artisanat-et-costumes.html"),
    ("Saluva", "Vêtement drapé emblématique des femmes de Mayotte (on écrit aussi salouva).", "culture/artisanat-et-costumes.html"),
    ("Shikomori", "Langue comorienne, de la famille bantoue, proche du swahili.", "culture/langues.html"),
    ("Shirazi", "Nom des lignées nobles qui se disent descendantes de princes venus de Shiraz, en Perse.", "histoire/premiers-peuplements.html"),
    ("Sultan tibe", "Titre du sultan suzerain de la Grande Comore, disputé entre les différents sultanats.", "histoire/le-temps-des-sultans.html"),
    ("Twarab", "Musique d'origine zanzibarite, mêlant influences arabes et africaines, jouée lors des mariages.", "culture/musique-et-danses.html"),
    ("Wadaha", "Danse féminine du pilon, rythmée par le pilage du riz dans un mortier.", "culture/musique-et-danses.html"),
    ("Ylang-ylang", "Arbre dont les fleurs produisent une huile essentielle très prisée en parfumerie, emblème des « îles aux parfums ».", "experiences/route-des-parfums.html"),
]

QUIZ = [
    dict(q="Quelle est l'île la plus ancienne de l'archipel ?",
         choices=["La Grande Comore", "Mohéli", "Anjouan", "Mayotte"], answer=3,
         explain="Mayotte est la doyenne : érodée et affaissée, elle est entourée d'un immense lagon. La Grande Comore est la plus jeune."),
    dict(q="Quelle est l'altitude du Karthala ?",
         choices=["1 595 m", "2 361 m", "3 070 m", "660 m"], answer=1,
         explain="Le Karthala culmine à 2 361 m. 1 595 m est l'altitude du mont Ntingui, à Anjouan."),
    dict(q="Comment appelle-t-on Anjouan en comorien ?",
         choices=["Ngazidja", "Mwali", "Ndzuwani", "Maore"], answer=2,
         explain="Ndzuwani est Anjouan. Ngazidja est la Grande Comore, Mwali Mohéli et Maore Mayotte."),
    dict(q="Quel poisson « fossile vivant » vit dans les eaux profondes des Comores ?",
         choices=["Le cœlacanthe", "Le requin-baleine", "Le poisson-clown", "L'espadon"], answer=0,
         explain="Le cœlacanthe, apparu il y a plus de 400 millions d'années, vit entre 150 et 250 m de profondeur."),
    dict(q="En quelle année les Comores ont-elles proclamé leur indépendance ?",
         choices=["1960", "1968", "1975", "1981"], answer=2,
         explain="L'indépendance a été proclamée le 6 juillet 1975."),
    dict(q="Qu'est-ce que le msindzano ?",
         choices=["Une danse", "Un masque de beauté au santal", "Un plat au coco", "Un instrument de musique"], answer=1,
         explain="Le msindzano est une pâte de bois de santal râpé sur du corail, appliquée sur le visage."),
    dict(q="Comment s'appelle le grand mariage en Grande Comore ?",
         choices=["Le anda", "Le debaa", "Le twarab", "Le kusi"], answer=0,
         explain="Le anda est le grand mariage coutumier. Le debaa est une danse, le twarab une musique et le kusi une saison."),
    dict(q="Quelle fleur a valu aux Comores le surnom d'« îles aux parfums » ?",
         choices=["Le jasmin", "La rose", "L'ylang-ylang", "Le frangipanier"], answer=2,
         explain="L'archipel est l'un des grands producteurs mondiaux d'huile essentielle d'ylang-ylang."),
    dict(q="Quelle mosquée possède un mihrab daté de 1538 ?",
         choices=["La mosquée du Vendredi de Moroni", "La mosquée de Tsingoni", "La mosquée de Domoni", "La mosquée de Fomboni"], answer=1,
         explain="Le mihrab de la mosquée de Tsingoni, à Mayotte, porte la date de 1538."),
    dict(q="Depuis quand Mayotte est-elle un département français ?",
         choices=["1946", "1976", "2011", "2018"], answer=2,
         explain="Mayotte est devenue le 101e département français le 31 mars 2011."),
]

FACTS = [
    "Le nom des Comores viendrait de l'arabe « Djazaïr al-Qamar », les îles de la Lune.",
    "La caldeira du Karthala est l'un des plus vastes cratères sommitaux de volcan actif au monde.",
    "Un nouveau volcan sous-marin, Fani Maoré, est né en 2018 à 50 km de Mayotte.",
    "Marseille est parfois surnommée la « cinquième île » des Comores.",
    "La vanille comorienne est pollinisée à la main, fleur par fleur.",
    "L'esclavage a été aboli à Mayotte dès 1846.",
]
